### ISSUE TITLE
Exercise planning

### ISSUE THREAD

**Issue by AydinHassan** [php-school/php8-appreciate#1]
### Which features to cover

First up we need to pick around 10 features from PHP 8 that we want to create exercises for. Maybe we can create a list of the features and make a vote?

### Exercise names

Then we need to decide on good names for the exercises

### Exercise briefs

We need to think how to translate the feature into an exercise, what will the brief be?

### Plan the exercise verification

How can we verify this particular exercise? Will we need new checks? Upgrade PHP Parser? 

### Start building

Then I guess we pick an exercise each, build, rinse and repeat

**Comment by AydinHassan** [comment]
@mikeymike

**Comment by mikeymike** [comment]
Sounds like a solid plan 👌

**Comment by mikeymike** [comment]
So quick list taken from the announcement page: 

- [x] [Named Arguments](https://www.php.net/releases/8.0/en.php#named-arguments)
- [ ] [Attributes](https://www.php.net/releases/8.0/en.php#attributes)
- [x] [Constructor property promotion](https://www.php.net/releases/8.0/en.php#constructor-property-promotion)
- [x] [Union types](https://www.php.net/releases/8.0/en.php#union-types)
- [x] [Match expression](https://www.php.net/releases/8.0/en.php#match-expression)
- [x] [Nullsafe operator](https://www.php.net/releases/8.0/en.php#nullsafe-operator)
- [ ] [Saner string to number comparisons](https://www.php.net/releases/8.0/en.php#saner-string-to-number-comparisons)
- [ ] [Consistent type errors for internal functions](https://www.php.net/releases/8.0/en.php#consistent-type-errors-for-internal-functions)
- [ ] Just-In-Time compilation
- [x] Non-capturing catches
- [x] Throw is now an expression
- [x] Static return type
- [ ] Weak Map
- [x] Stringable
- [x] str_contains(), str_starts_with(), str_ends_with()
- [x] fdiv

Things I don't personally think fit the format: 
- JIT 
- Consistent type errors for internal functions
- Saner string to number comparisons

Possibly WeakMap too 🤔 

The rest I feel like they have good merit for inclusion.

**Comment by mikeymike** [comment]
@AydinHassan I think it would be beneficial to break out the ones we want to do into new issues with some formal format where we can refine each one into something "implementable" 

Thinking back to the idea of a vote, are you thinking a public poll to get community feedback?

**Comment by AydinHassan** [comment]
@mikeymike yeah that sounds good to me. I was thinking just for us to be honest rather than a community poll. We can tweet and ask for feedback on our decision though. 

Looking back over your list it seems like we could probably do all of them minus the ones we don't think fit. So there is 16 in total and if we take off JIT, Consistent type errors, Saner string to number comparisons that's 13. I'd probably drop `fdiv` as well, that's a bit boring so that leaves us with 12. 

What do you think?

**Comment by mikeymike** [comment]
👌 Sounds perfect, I'll break them into separate tasks on the board and we can work on naming, briefs etc 🎉

**Comment by mikeymike** [comment]
Ok so I created a bunch of issues with empty templates, I think we discuss each one individually and build out the main issue as we go (just by editing it 😄 ) 

The only one I wasn't sure on was WeakMap... you think we can make that fit the structure ?
