### ISSUE TITLE
Attributes

### ISSUE THREAD

**Issue by mikeymike** [php-school/php8-appreciate#3]
**Name:** The attributes of success

## Brief

- Provide a function which takes a json string and a class string. It deserialises the json and attempts to populate the given class reading the annotations to describe how the object should be mapped/populated. We can use attributes like `Map`, `Skip`, `Deserialise` (to annotate that the class can be used in deserialisation)

The user should write a class which represents some json data that we will pass to them, they must call the function with their class and the given data.

## Verification

This one might be a bit trickier to verify, I'm not sure what output we should expect. We could just `var_dump` the object in our function to verify the structure of it.

**Comment by AydinHassan** [comment]
metadata, meta (make: pun???) , information, attributing, docblocks, "Meta my docblocks better", "The attributes of success"
