### ISSUE TITLE
Have the Last Say - csv file

### ISSUE THREAD

**Issue by jason37** [php-school/php8-appreciate#37]
Are we supposed to create the country|capital csv file for this exercise? When I run verify on my code, the test runs against a random country|capital list so it fails because the output based on my country list doesn't match the random list the test uses.

**Comment by mikeymike** [comment]
Hey @jason37 ... The CSV file will be generated on each run of the exercise (either by verify or run) and passed into your solution as an argument. 

In your solution try running `var_dump($argv);`, you'll notice one of the arguments passed in is a path, this path will change on each run of the exercise so you'll need to use the value passed in each time. 

Hope that helps, feel free to join our [Slack Group](https://phpschool.herokuapp.com/) if you'd like some more assistance from the community

**Comment by jason37** [comment]
Thanks! I missed that detail in the assignment description.

**Comment by AydinHassan** [comment]
@jason37 just in case you didn't know - you can use `php8appreciate print` to print the instructions again :)
