### ISSUE TITLE
Throw is now an Expression

### ISSUE THREAD

**Issue by mikeymike** [php-school/php8-appreciate#9]
**Name:** Throw an expression

## Brief

Throw being an expression makes it possible to use it in various new places in the language. 

- Provide an example `if` statement that has an else branch which throws an exception
- Ask them to rewrite this in a more terse format utilising the benefits of throw as an expression

Hint we expect to see a ternary

## Verification

- AST parsing to check the token is used in a ternary
- Ensure exception is thrown under expected use

**Comment by mikeymike** [comment]
@AydinHassan updated, let me know what you think

**Comment by AydinHassan** [comment]
@mikeymike perfect!
